# Generated by Django 5.1.2 on 2024-11-11 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'db_table': 'types',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.type'),
        ),
    ]
